name: ESLint
on:
  pull_request:  
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --no-audit 
    - name: Run ESLint
      run: npx eslint src
